const TREASURES = [
  {
    id: 1,
    name: "Laboratorio de Pallet",
    map: { x: 280, y: 610 },
    emoji: "PK",
    type: "Eletrico",
    color: "#ffcb05",
    quiz: {
      question: "O Pokemon misterioso desta rota guarda energia nas bochechas e usa choques eletricos. Quem e ele?",
      options: ["Bulbasaur", "Charmander", "Squirtle", "Pikachu"],
      correct: 3,
    },
    clue: {
      full: "Pikachu solta o primeiro raio.",
      partial: "??????? solta o primeiro raio.",
    },
    pokemon: {
      dex: 25,
      name: "Pikachu",
      sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
    },
    description: "Energia eletrica, coragem e o primeiro passo da equipe.",
    battle: {
      hp: 92,
      attack: 25,
      special: 43,
      move: "Choque do Trovao",
      specialMove: "Investida Eletrica",
    },
  },
  {
    id: 2,
    name: "Floresta de Viridian",
    map: { x: 520, y: 355 },
    emoji: "GR",
    type: "Grama",
    color: "#62d77a",
    quiz: {
      question: "O Pokemon misterioso tem uma semente nas costas desde que nasce. Quem e ele?",
      options: ["Oddish", "Bulbasaur", "Chikorita", "Bellsprout"],
      correct: 1,
    },
    clue: {
      full: "Bulbasaur guarda a semente da rota.",
      partial: "????????? guarda a semente da rota.",
    },
    pokemon: {
      dex: 1,
      name: "Bulbasaur",
      sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
    },
    description: "Um parceiro tranquilo que conhece cada trilha da floresta.",
    battle: {
      hp: 112,
      attack: 20,
      special: 36,
      move: "Chicote de Vinha",
      specialMove: "Raio Solar",
    },
  },
  {
    id: 3,
    name: "Vulcao Cinnabar",
    map: { x: 760, y: 585 },
    emoji: "FG",
    type: "Fogo",
    color: "#ff8a3d",
    quiz: {
      question: "O Pokemon misterioso mantem uma chama acesa na ponta da cauda. Quem e ele?",
      options: ["Vulpix", "Charmander", "Ponyta", "Magmar"],
      correct: 1,
    },
    clue: {
      full: "Charmander acende a chama do caminho.",
      partial: "?????????? acende a chama do caminho.",
    },
    pokemon: {
      dex: 4,
      name: "Charmander",
      sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
    },
    description: "A chama na cauda ilumina cavernas, rotas e respostas.",
    battle: {
      hp: 96,
      attack: 24,
      special: 42,
      move: "Brasa",
      specialMove: "Lanca-Chamas",
    },
  },
  {
    id: 4,
    name: "Torre de Lavanda",
    map: { x: 1010, y: 320 },
    emoji: "GH",
    type: "Fantasma",
    color: "#a889ff",
    quiz: {
      question: "O Pokemon misterioso e feito de gas venenoso e aparece como uma esfera fantasma. Quem e ele?",
      options: ["Gastly", "Onix", "Pidgey", "Lapras"],
      correct: 0,
    },
    clue: {
      full: "Gastly revela o segredo na neblina.",
      partial: "?????? revela o segredo na neblina.",
    },
    pokemon: {
      dex: 92,
      name: "Gastly",
      sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png",
    },
    description: "Leve como gas, perfeito para achar pistas escondidas.",
    battle: {
      hp: 82,
      attack: 27,
      special: 45,
      move: "Lambida",
      specialMove: "Bola Sombria",
    },
  },
  {
    id: 5,
    name: "Liga Indigo",
    map: { x: 1210, y: 690 },
    emoji: "AG",
    type: "Agua",
    color: "#57c7ff",
    quiz: {
      question: "O Pokemon misterioso e uma pequena tartaruga de casco duro e tipo Agua. Quem e ele?",
      options: ["Psyduck", "Totodile", "Squirtle", "Poliwag"],
      correct: 2,
    },
    clue: {
      full: "Squirtle fecha a equipe com agua clara.",
      partial: "???????? fecha a equipe com agua clara.",
    },
    pokemon: {
      dex: 7,
      name: "Squirtle",
      sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
    },
    description: "O casco aguenta a pressao da batalha final.",
    battle: {
      hp: 118,
      attack: 21,
      special: 38,
      move: "Jato de Agua",
      specialMove: "Hidro Bomba",
    },
  },
];

export default TREASURES;
